name: Shovel Bucket Minion
description: Set of actions to automate Shovel bucket maintaining.
author: Jakub <Ash258> Čábera
runs:
    using: composite
    steps:
      - run: ${{ github.action_path }}/action.ps1
        shell: pwsh
branding:
    icon: package
    color: purple
